[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
        "-C",
        "passes=lower-atomic",
        "-C",
        "link-arg=-Ttext=0x00201000",
        "-C",
        "link-arg=--image-base=0x00200800",
        "-C",
        "panic=abort",
        "--cfg",
        "getrandom_backend=\"custom\"",
]
